version: "3.7"
services:
  ash:
    entrypoint: /bin/ash
    build:
      context: ../contexts/binary/.
      dockerfile: ../../dockerfiles/binaries/ash
    volumes:
      - $PWD:/home/docker.worker/run
      - php:/mnt/php:ro
      - apache:/mnt/apache:ro
      - python:/mnt/python:ro
      - node:/mnt/node:ro
      - ruby:/mnt/ruby:ro
      - go:/mnt/go:ro
  crond:
    entrypoint: /usr/sbin/crond
    command: '-f'
    build:
      context: ../contexts/binary/.
      dockerfile: ../../dockerfiles/binaries/crond
    volumes:
      - $PWD:/home/docker.worker/run
      - crond:/mnt/xprt
  apache:
    entrypoint: /bin/ash
    build:
      context: ../contexts/binary/.
      dockerfile: ../../dockerfiles/binaries/apache
    volumes:
      - $PWD:/home/docker.worker/run
      - apache:/mnt/xprt
  php:
    entrypoint: /usr/bin/php
    build:
      context: ../contexts/binary/.
      dockerfile: ../../dockerfiles/binaries/php
    volumes:
      - $PWD:/home/docker.worker/run
      - php:/mnt/xprt
  composer:
    entrypoint: /usr/bin/composer
    image: binaries_php
    volumes:
      - $PWD:/home/docker.worker/run
      - php:/mnt/xprt
  node:
    entrypoint: /usr/bin/node
    build:
      context: ../contexts/binary/.
      dockerfile: ../../dockerfiles/binaries/node
    volumes:
      - $PWD:/home/docker.worker/run
      - node:/mnt/xprt
  npm:
    entrypoint: /usr/bin/npm
    image: binaries_node
    volumes:
      - $PWD:/home/docker.worker/run
      - node:/mnt/xprt
  ruby:
    entrypoint: /usr/bin/ruby
    build:
      context: ../contexts/binary/.
      dockerfile: ../../dockerfiles/binaries/ruby
    volumes:
      - $PWD:/home/docker.worker/run
      - ruby:/mnt/xprt
  gem:
    entrypoint: /usr/bin/ruby
    image: binaries_ruby
    volumes:
      - $PWD:/home/docker.worker/run
      - ruby:/mnt/xprt
  python:
    entrypoint: /usr/bin/python
    build:
      context: ../contexts/binary/.
      dockerfile: ../../dockerfiles/binaries/python
    volumes:
      - $PWD:/home/docker.worker/run
      - python:/mnt/xprt
  pip:
    entrypoint: /usr/bin/pip
    image: binaries_python
    volumes:
      - $PWD:/home/docker.worker/run
      - python:/mnt/xprt
  go:
    entrypoint: /usr/bin/go
    build:
      context: ../contexts/binary/.
      dockerfile: ../../dockerfiles/binaries/go
    volumes:
      - $PWD:/home/docker.worker/run
      - go:/mnt/xprt
volumes:
  crond:
    name: binaries_crond
  php:
    name: binaries_ash
  node:
    name: binaries_node
  ruby:
    name: binaries_ruby
  python:
    name: binaries_python
  go:
    name: binaries_go
  apache:
    name: binaries_apache
  memory:
    name: memory
    driver_opts:
      type: tmpfs
      device: tmpfs